### ISSUE TITLE
OS does not support terminal-notifier

### ISSUE THREAD

**Issue by aarongorka** [dreadl0ck/zeus#12] opened 2019-01-23 03:06 UTC
Receiving this output on every command I run with zeus, e.g.:

```bash
$ zeus -h
2019/01/23 14:04:46 OS does not support terminal-notifier
ZEUS - An Electrifying Build System
author: dreadl0ck@protonmail.ch
for documentation see: https://github.com/dreadl0ck/zeus
run 'zeus bootstrap' to create a default ZEUS setup
or 'zeus makefile migrate' if you want to migrate from a GNU Makefile.
to get an overview over an existing ZEUS project, run 'zeus help' or 'zeus' for the interactive shell.
```

It's not fatal but I'm guessing not intended.

I'm running on Linux:

```bash
$ uname -a
Linux linux 4.19.14-300.fc29.x86_64 #1 SMP Wed Jan 9 21:30:35 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

With zeus 0.8.4.

**Comment by dreadl0ck** [comment] 2019-02-18 19:36
Hi there,

thanks for reporting and sorry for the late reply!

The issue is fixed on master (now using a cross platform package for the notifications).

Cheers

**Closed by dreadl0ck** 2019-02-18 19:36 UTC
